### ISSUE TITLE
Headers in string when converting

### ISSUE THREAD

**Issue by scarfdestroyer** [AddJam/ember-image-drop#5] opened 2016-01-28 22:21 UTC
Ember image drop currently puts header information at the beginning of the file so the browser knows how to read it. In our use case (an ember front end, rails back end) when we try and read the output string rails interprets it as an application/octet-stream MIME attachment. This makes it so we have to use regex in order to remove the header/use the string. Is your recommended use case one where you want to be sending a base64 string or the actual file?

**Comment by chrissloey** [comment] 2016-01-29 13:07
The addon supports both use cases - I've used it for sending base64 to a Rails backend (and then storing the data with paperclip) and also used it for sending files directly to S3.

When I used it to send base64 to rails it was in some json, which might be why I never encountered the content type problems you're facing?

**Comment by joshsmith** [comment] 2016-01-29 22:41
@chrissloey weird, because this is our exact use case: sending base64 string to a Rails backend to be processed by Paperclip.

In our case, we have a method for decoding this data:

``` ruby
def decode_image_data
  return unless base64_photo_data.present?
  data = StringIO.new(Base64.decode64(base64_photo_data))
  data.class.class_eval { attr_accessor :original_filename, :content_type }
  data.original_filename = SecureRandom.hex + ".png"
  data.content_type = "image/png"
  self.photo = data
end
```

This is used in a worker that handles all this processing.

Paperclip thinks it's spoofed for some reason. The issue is replicated by `PATCH`-ing, this time in an `input` instead of using the component. Removing the `data:image/png;base64,` and doing the same thing will pick up the correct content type.

While I know we're getting a little far from Ember specifics here, it could be instructive if you shared how you're processing in your Rails backend currently.

**Comment by joshsmith** [comment] 2016-01-29 22:44
To clarify, too, everything after the `,` are the bytes in the base64; everything including preceding that comma is technically not part of a base64 string.

**Comment by chrissloey** [comment] 2016-02-03 11:25
I use the Data URI and let paperclip decode it rather than parsing out just the Base64 and decoding it myself.

The answer here works fine for me http://stackoverflow.com/questions/25521331/rails-4-paperclip-upload-an-image-using-data-uri

Data URI is just embedded as a string in the JSON I'm sending - not sure why you're having issues with `application/octet-stream`. E.g.

```
{
  "model": {
    "image": "data:image/png;base64,iVBORw0KGgoAAAANSUh..."
  }
}
```

**Comment by joshsmith** [comment] 2016-02-07 23:23
@chrissloey thanks for this. I will try this out this afternoon and report back if it works for me. It seems like this is more a Paperclip/me issue than it is an issue here.

**Comment by joshsmith** [comment] 2016-02-07 23:24
I will note that your method is also significantly cleaner than our current implementation. I just need to verify it works with fixtures that both include the `data` URI and those that do not.

**Comment by chrissloey** [comment] 2016-03-01 14:37
Closing this - hope you got it all sorted :smile:

**Closed as completed by chrissloey** 2016-03-01 14:37 UTC
